### ISSUE TITLE
[Question] No information on how contribute.

### ISSUE THREAD

**Issue by jristz** [legionus/kbd#5]
I was reading the webpage and this mirror but I noticed there is no information available on how contribute.

Actually the page just point on cloning the repo and get the latest version but nothing more, and the mailist look abandoned.

So this raise question like

* Is there a standard coding?
* I send a patch to the mailist, a pull request here or a patch in a bugzilla (that either is not mentioned)?
* Is there a concientrated place on where check abailable patches?

Could you either add that info (or at least a "contribute patch here <inser github/bugzilla/mailist>") for other that want contributing?

**Comment by legionus** [comment]
@jristz I didn't think that such information is necessary since I get not too much patches. But such information can be added once needed.

Here quick answers (I will add them to website):

> Is there a standard coding?

I have a config for [clang-format](https://github.com/legionus/kbd/blob/master/.clang-format) for this purpose.

> I send a patch to the mailist, a pull request here or a patch in a bugzilla (that either is not mentioned)?

Patches are accepted via the mailing list. There they are discussed.

> Is there a concientrated place on where check abailable patches?

I'm not sure I understand the question.

**Comment by jristz** [comment]
> > Is there a concientrated place on where check abailable patches?
> I'm not sure I understand the question.
I mean if there is a To-Do list.

> Patches are accepted via the mailing list. There they are discussed.
I asked because the mailist look kinda... abandoned, and on the keymaps folder the readme mention a different mail <aeb@cwi.nl>

**Comment by legionus** [comment]
> I mean if there is a To-Do list.

I have a TODO and I try to move on it. However, I did not publish it anywhere because no one shows interest.

> I asked because the mailist look kinda... abandoned

This is not true. The guys from RedHat and Gentoo subscribed on this maillist. They tell me about the issues and send patches. Yes, the community of the project is not very active :)

> on the keymaps folder the readme mention a different mail aeb@cwi.nl

This is the previous developer. I don't want to clean up his address. Also he forwards me emails about this kbd.

**Comment by legionus** [comment]
done.

**Comment by jristz** [comment]
Done, thanks. 

I will do the thing and use that mailist. 
Thanks again.
