### ISSUE TITLE
[KEYMAP] mac-fr.map

### ISSUE THREAD

**Issue by MetotoSakamoto** [legionus/kbd#73]
With archlinux ISO installer which is based from upstream kbd, enter:
`loadkeys mac-fr`
return a weird and unusable layout.

**Comment by legionus** [comment]
@MetotoSakamoto Please attach `fr-mac-suse` keymap here.

**Comment by legionus** [comment]
> [fr-mac.map.gz](https://github.com/legionus/kbd/files/8382301/fr-mac.map.gz)

omg. This is just a dump. If it works for you then great. Use it.

**Comment by legionus** [comment]
I haven't checked yet, but it looks like the keymap is for modern keyboards and not for Macintosh.

**Comment by Montagnard** [comment]
Which keymap is to be used for modern macbook pro ?

**Comment by legionus** [comment]
For modern macbook pro you should use `keymaps/i386/qwerty/fi.map` or any other keymap from the `i386`.

**Comment by nsklaus** [comment]
this is a general problem for all linux users on macbooks.
very few people notice about this, because people are very rarely in tty.
even heavy term users are using term from X or wayland.
but when in tty, macbook users are left with a generic "us" or generic "fr" or generic "de" keymap,
it prevent them from inputing correctly chars like: "~", "/", "|",  and so on ...
trying to load a more correct keymap, instead of the generic one, like doing:
`loadkeys mac-fr` (or mac-de, mac-us, .....) leaves the keymap in a completely broken state.
for example inputing "azerty" gives something like "yulksdf"  .. 
completely broken. it's not even possible to type "shutdown -h now" to power off the system.
not possible to switch to another tty (since keymap is completely scrambled).

to note:
this problem concerns all macbook (mac-us, mac-fr, mac-de, ..) users, in tty, when using arch linux for example.
this problem does *not* happen on fedora, and apparently opensuse, and a few other distros.
i have noticed this problem maybe like 10years ago, and it is still there.

since i like to use arch, i usualy pick the mac-fr.map.gz from another distro and copy it over my arch install. my guess is that kbd have a problem with macbook keymap, and some distro have worked around it, and some other did not.
